// Dados — Sanka Burguers

export const SANKA_CATS = [
  { id: "classicos", label: "Clássicos" },
  { id: "queijos", label: "Queijos & Mel" },
  { id: "carnes", label: "Carnes Especiais" },
  { id: "frango", label: "Frango" },
  { id: "vegetal", label: "Vegetais" },
];

export const SANKA_BURGERS = [
  {
    name: "X Misto",
    cat: "classicos",
    code: "SB-001",
    desc: "O começo de tudo. Hambúrguer artesanal 120g, presunto, queijo prato derretido e o pão sankinha selado na chapa.",
    price: 18.9,
    tag: null,
    tags: "burger,cheese",
    src: "/assets/burgers/sb-001.png",
  },
  {
    name: "Hot Dog",
    cat: "classicos",
    code: "SB-002",
    desc: "Salsicha bovina premium, molho de tomate da casa, milho doce, batata palha crocante e parmesão fino por cima.",
    price: 16.5,
    tag: null,
    tags: "hotdog,sausage",
    src: "/assets/burgers/sb-002.png",
  },
  {
    name: "X Americano",
    cat: "classicos",
    code: "SB-003",
    desc: "Hambúrguer 150g grelhado no ponto, queijo cheddar, ovo caipira, alface fresca, tomate e maionese da casa.",
    price: 24.9,
    tag: "FAVORITO",
    tags: "cheeseburger,egg",
    src: "/assets/burgers/sb-003.png",
  },
  {
    name: "X Provolone ao Mel",
    cat: "queijos",
    code: "SB-004",
    desc: "Provolone defumado fatiado, regado com fio de mel silvestre direto na chapa. Doce, salgado, viciante.",
    price: 28.9,
    tag: "ASSINATURA",
    tags: "burger,honey",
    src: "/assets/burgers/sb-004.png",
  },
  {
    name: "X Acebolado",
    cat: "classicos",
    code: "SB-005",
    desc: "Carne 150g, queijo prato, cebola caramelizada lentamente em manteiga até virar geleia dourada.",
    price: 26.9,
    tag: null,
    tags: "burger,onion",
    src: "/assets/burgers/sb-005.png",
  },
  {
    name: "X Provolone",
    cat: "queijos",
    code: "SB-006",
    desc: "Provolone derretido em camada grossa sobre carne 150g, alface, tomate e maionese verde.",
    price: 27.9,
    tag: null,
    tags: "burger,provolone",
    src: "/assets/burgers/sb-006.png",
  },
  {
    name: "X Biquinho",
    cat: "queijos",
    code: "SB-007",
    desc: "Carne suculenta, cream cheese, pimenta biquinho em conserva e cebola roxa. Levemente picante, intensamente gostoso.",
    price: 29.9,
    tag: null,
    tags: "burger,pepper",
    src: "/assets/burgers/sb-007.png",
  },
  {
    name: "X Egg",
    cat: "classicos",
    code: "SB-008",
    desc: "Carne 150g, ovo caipira com gema mole, queijo prato e bacon em tiras. Café da manhã que virou jantar.",
    price: 25.9,
    tag: null,
    tags: "burger,egg",
    src: "/assets/burgers/sb-008.png",
  },
  {
    name: "X Hamburgão",
    cat: "carnes",
    code: "SB-009",
    desc: "Duas carnes 150g empilhadas, duas fatias de cheddar, bacon crocante e molho barbecue defumado. Tamanho família.",
    price: 39.9,
    tag: "TOP 3",
    tags: "burger,double",
    src: "/assets/burgers/sb-009.png",
  },
  {
    name: "X Frango",
    cat: "frango",
    code: "SB-010",
    desc: "Filé de frango grelhado marinado em alho e ervas, queijo prato, alface americana e maionese da casa.",
    price: 26.9,
    tag: null,
    tags: "chicken,burger",
    src: "/assets/burgers/sb-010.png",
  },
  {
    name: "X Frango Catupiry",
    cat: "frango",
    code: "SB-011",
    desc: "Frango desfiado refogado, catupiry cremoso original derretendo por cima, alface e tomate fresco.",
    price: 28.9,
    tag: null,
    tags: "chicken,burger,cheese",
    src: "/assets/burgers/sb-011.png",
  },
  {
    name: "X Calabresa",
    cat: "carnes",
    code: "SB-012",
    desc: "Calabresa artesanal fatiada na chapa, queijo mussarela, cebola caramelizada e maionese de alho.",
    price: 27.9,
    tag: null,
    tags: "burger,sausage",
    src: "/assets/burgers/sb-012.png",
  },
  {
    name: "X Azeitonado",
    cat: "carnes",
    code: "SB-013",
    desc: "Carne 150g, queijo prato, azeitona preta picada, orégano e azeite extra virgem. Memória de pizza de domingo.",
    price: 27.9,
    tag: null,
    tags: "burger,olive",
    src: "/assets/burgers/sb-013.png",
  },
  {
    name: "X Brócolis Catupiry",
    cat: "vegetal",
    code: "SB-014",
    desc: "Brócolis refogado no alho, catupiry cremoso, queijo prato derretido e toque de pimenta do reino.",
    price: 28.9,
    tag: "NOVO",
    tags: "broccoli,burger",
  },
  {
    name: "X Panceta",
    cat: "carnes",
    code: "SB-015",
    desc: "Panceta crocante fatiada finíssima sobre carne 150g, cheddar inglês, rúcula e maionese defumada.",
    price: 34.9,
    tag: "ASSINATURA",
    tags: "burger,pancetta",
    src: "/assets/burgers/sb-015.png",
  },
  {
    name: "X Bacon",
    cat: "carnes",
    code: "SB-016",
    desc: "Bacon crocante em camada generosa, carne 150g, cheddar duplo, cebola caramelizada e molho da casa.",
    price: 31.9,
    tag: "FAVORITO",
    tags: "burger,bacon",
    src: "/assets/burgers/sb-016.png",
  },
  {
    name: "X Bacon Azeitonado",
    cat: "carnes",
    code: "SB-017",
    desc: "Combinação ousada. Bacon crocante, azeitona preta, mussarela derretida, orégano e maionese de ervas.",
    price: 33.9,
    tag: null,
    tags: "burger,bacon,olive",
    src: "/assets/burgers/sb-017.png",
  },
];

export const SANKA_EXTRAS = [
  { name: "Catupiry", price: 4.0, ico: "◐" },
  { name: "Cheddar",  price: 4.0, ico: "❒" },
  { name: "Ovo",      price: 3.0, ico: "◯" },
  { name: "Bacon",    price: 6.0, ico: "≡" },
  { name: "Cebola Caramelizada", price: 4.0, ico: "✦" },
  { name: "Milho",    price: 3.0, ico: "◉" },
  { name: "Carne Adicional",     price: 9.0, ico: "▰" },
  { name: "Provolone", price: 5.0, ico: "◧" },
  { name: "Cream Cheese", price: 4.0, ico: "◑" },
  { name: "Mussarela", price: 4.0, ico: "▤" },
  { name: "Calabresa", price: 5.0, ico: "≣" },
  { name: "Frango Desfiado", price: 6.0, ico: "▱" },
  { name: "Pimenta Biquinho", price: 3.0, ico: "◆" },
  { name: "Jalapeño", price: 4.0, ico: "♢" },
  { name: "Picles", price: 3.0, ico: "⊜" },
  { name: "Rúcula", price: 3.0, ico: "✺" },
  { name: "Cebola Roxa", price: 2.0, ico: "◔" },
  { name: "Molho da Casa Extra", price: 2.0, ico: "◌" },
  { name: "Barbecue Defumado", price: 3.0, ico: "◍" },
  { name: "Maionese Verde", price: 3.0, ico: "◎" },
  { name: "Azeitona Preta", price: 3.0, ico: "●" },
];

export const SANKA_DRINKS = [
  {
    name: "Suco de Laranja Natural",
    desc: "Espremido na hora. Sem açúcar, sem água, sem desculpa.",
    price: 12.0,
    tag: "Natural",
    bg: "linear-gradient(155deg, #ff9a3c 0%, #e0581a 60%, #7a2900 100%)",
  },
  {
    name: "Suco Laranja com Açaí",
    desc: "A explosão tropical com a profundidade do açaí amazônico.",
    price: 16.0,
    tag: "Combo",
    bg: "linear-gradient(155deg, #ff8a3c 0%, #6a2a8a 65%, #1a0a3a 100%)",
  },
  {
    name: "Suco de Açaí",
    desc: "Açaí puro batido na hora. Cremoso, gelado, intenso.",
    price: 14.0,
    tag: "Puro",
    bg: "linear-gradient(155deg, #5e2a8a 0%, #2a0a4a 70%, #0a0014 100%)",
  },
  {
    name: "Açaí com Leite Condensado",
    desc: "A doçura que abraça o azedinho. Sobremesa em copo.",
    price: 16.0,
    tag: "Doce",
    bg: "linear-gradient(155deg, #b88aff 0%, #6a3a9a 55%, #2a0a4a 100%)",
  },
  {
    name: "Limonada Suíça",
    desc: "Limão batido com casca, leite condensado e muito gelo. Cremosa e refrescante.",
    price: 13.0,
    tag: "Refresca",
    bg: "linear-gradient(155deg, #b8e88a 0%, #4a7a2a 60%, #1a3a0a 100%)",
  },
  {
    name: "Suco de Maracujá",
    desc: "Polpa fresca peneirada, açúcar na medida e gelo. Azedinho equilibrado.",
    price: 13.0,
    tag: "Natural",
    bg: "linear-gradient(155deg, #ffd24a 0%, #d8941a 55%, #4a2a00 100%)",
  },
  {
    name: "Suco de Uva Integral",
    desc: "Uva integral 100% sem açúcar adicionado. Servido bem gelado em copo alto.",
    price: 11.0,
    tag: "Integral",
    bg: "linear-gradient(155deg, #7a2a8a 0%, #3a0a4a 60%, #1a0214 100%)",
  },
  {
    name: "Mate Gelado da Casa",
    desc: "Chá mate tostado infusionado a frio, com fatia de limão e folhas de hortelã.",
    price: 10.0,
    tag: "Gelado",
    bg: "linear-gradient(155deg, #c8a05a 0%, #6a4a2a 55%, #2a1a0a 100%)",
  },
  {
    name: "Refrigerante Lata 350ml",
    desc: "Coca-Cola, Coca Zero, Guaraná Antarctica, Sprite ou Fanta. Sempre gelada.",
    price: 7.0,
    tag: "350ml",
    bg: "linear-gradient(155deg, #2a2a2a 0%, #1a0a0a 100%)",
  },
  {
    name: "Refrigerante 2L",
    desc: "Pra dividir na mesa. Coca-Cola, Guaraná ou Sprite — escolhe na finalização.",
    price: 14.0,
    tag: "2 Litros",
    bg: "linear-gradient(155deg, #c92a1f 0%, #4a0a0a 60%, #1a0202 100%)",
  },
  {
    name: "Água Mineral",
    desc: "Com ou sem gás. Garrafa 500ml, sempre gelada. Pede no quente também.",
    price: 5.0,
    tag: "500ml",
    bg: "linear-gradient(155deg, #6aa0d4 0%, #1a3a6a 60%, #0a1428 100%)",
  },
  {
    name: "Batida Açaí & Laranja",
    desc: "Vodka, açaí cremoso e laranja na medida. Drink autoral da casa.",
    price: 22.0,
    tag: "18+",
    bg: "linear-gradient(155deg, #ff8a4a 0%, #8a2a6a 55%, #2a0a3a 100%)",
  },
  {
    name: "Batida Açaí & Morango",
    desc: "Morango fresco, açaí encorpado e vodka prata. Drink dia de verão.",
    price: 22.0,
    tag: "18+",
    bg: "linear-gradient(155deg, #ff6a8a 0%, #8a2a4a 55%, #2a0a2a 100%)",
  },
  {
    name: "Caipirinha de Limão",
    desc: "Cachaça artesanal, limão tahiti macerado e açúcar mascavo. Da forma certa.",
    price: 20.0,
    tag: "18+",
    bg: "linear-gradient(155deg, #d4e88a 0%, #4a7a2a 55%, #1a2a0a 100%)",
  },
  {
    name: "Chopp Artesanal Pilsen",
    desc: "Pilsen leve da microcervejaria parceira do bairro. Servido em caneca gelada 400ml.",
    price: 16.0,
    tag: "18+",
    bg: "linear-gradient(155deg, #f5c44a 0%, #8a5a1a 55%, #2a1a05 100%)",
  },
];

export const SANKA_FEATURES = [
  { num: "01", title: "Ingredientes Selecionados", desc: "Hortifrúti diário, queijos da serra mineira, carne fresca moída na casa. Sem congelado, sem atalho.", icon: "leaf" },
  { num: "02", title: "Hambúrguer Artesanal", desc: "Blend exclusivo de acém, peito e fraldinha. Moído duas vezes, prensado leve, ponto suculento.", icon: "flame" },
  { num: "03", title: "Entrega Rápida", desc: "Saímos da chapa direto pra moto. Raio de 6km coberto em até 35 minutos ou o próximo é por nossa conta.", icon: "rocket" },
  { num: "04", title: "Molhos Exclusivos", desc: "Sete molhos da casa, desenvolvidos no balcão. Do barbecue defumado à maionese de ervas frescas.", icon: "drop" },
  { num: "05", title: "Sabor Marcante", desc: "Receita perfeita pela teimosia. Três anos testando até o cliente dizer que vicia. Não exageramos.", icon: "spark" },
  { num: "06", title: "Atendimento Premium", desc: "Pedido confirmado em segundos, status em tempo real, e atendente humano quando você precisa.", icon: "heart" },
];

export const SANKA_TESTIMONIALS = [
  { quote: "Melhor hambúrguer da cidade. Surreal.", stars: 5, name: "Mariana S.", meta: "Pedido #4827 · Cliente recorrente" },
  { quote: "A panceta deles é absurda. Voltei três vezes essa semana.", stars: 5, name: "Diego R.", meta: "Pedido #4901 · Cliente recorrente" },
  { quote: "X Provolone ao Mel mudou minha vida. Só isso.", stars: 5, name: "Camila A.", meta: "Pedido #4756 · Primeira vez" },
];

// ============================== COMBOS ==============================
export const SANKA_COMBOS = [
  {
    code: "CB-01",
    name: "Combo Clássico",
    items: ["X Americano", "Batata Frita Média", "Refrigerante 350ml"],
    desc: "O combo que abriu a casa. Carne 150g, ovo, queijo e a porção média perfeita pra dividir (ou não).",
    price: 38.9,
    full: 47.8,
    tag: "MAIS PEDIDO",
    serves: "1 pessoa",
    bg: "linear-gradient(155deg, #2a1a0a 0%, #14110d 100%)",
    tags: "burger,fries,cola",
  },
  {
    code: "CB-02",
    name: "Combo Bacon Lover",
    items: ["X Bacon", "Batata Cheddar & Bacon", "Suco de Laranja Natural"],
    desc: "Pra quem ama bacon em camadas. Hambúrguer recheado + porção coberta de cheddar derretido e bacon picado.",
    price: 54.9,
    full: 67.8,
    tag: "TOP 3",
    serves: "1 pessoa",
    bg: "linear-gradient(155deg, #2a0e05 0%, #1a0a08 100%)",
    tags: "bacon,burger,fries",
  },
  {
    code: "CB-03",
    name: "Combo Família",
    items: ["X Hamburgão", "Batata Especial Grande", "2 Refrigerantes 350ml"],
    desc: "Carne dupla, porção família de 600g com molhos e duas latinhas. Pega o controle e bora.",
    price: 79.9,
    full: 98.7,
    tag: "PRA DIVIDIR",
    serves: "2 pessoas",
    bg: "linear-gradient(155deg, #1a0e1a 0%, #0a0a14 100%)",
    tags: "burger,fries,combo",
  },
  {
    code: "CB-04",
    name: "Combo Sanka Premium",
    items: ["X Panceta", "Batata Rústica c/ Parmesão", "Batida Açaí & Morango"],
    desc: "A casa flexionando. Panceta crocante, batata rústica com parmesão e queijo gratinado, batida autoral.",
    price: 64.9,
    full: 78.8,
    tag: "ASSINATURA",
    serves: "1 pessoa",
    bg: "linear-gradient(155deg, #2a0a1a 0%, #1a0a14 100%)",
    tags: "burger,fries,cocktail",
  },
];

// ============================== PORÇÕES ==============================
export const SANKA_SIDES = [
  {
    code: "PR-01",
    name: "Batata Frita Simples",
    size: "300g",
    desc: "Batata palito, cortada fina, frita em óleo limpo. Sal grosso, crocante por fora, macia por dentro.",
    price: 18.9,
    tag: null,
    tags: "fries,frenchfries",
  },
  {
    code: "PR-02",
    name: "Batata Cheddar & Bacon",
    size: "400g",
    desc: "Batata coberta com cheddar inglês derretido e bacon crocante picado. A clássica que nunca decepciona.",
    price: 32.9,
    tag: "FAVORITO",
    tags: "fries,cheese,bacon",
  },
  {
    code: "PR-03",
    name: "Batata Especial Grande",
    size: "600g",
    desc: "Pra dividir mesmo. Batata, cheddar, bacon, cebola roxa, cebolinha e molhos da casa por cima.",
    price: 42.9,
    tag: "PRA DIVIDIR",
    tags: "loaded,fries,cheese",
  },
  {
    code: "PR-04",
    name: "Batata Rústica c/ Parmesão",
    size: "350g",
    desc: "Batata em gomos, com casca, alecrim fresco e parmesão gratinado por cima. Acompanha maionese verde.",
    price: 28.9,
    tag: null,
    tags: "potato,wedges,parmesan",
  },
  {
    code: "PR-05",
    name: "Onion Rings",
    size: "12 unid.",
    desc: "Anéis de cebola empanados na panko, fritos no ponto exato. Acompanha molho barbecue defumado da casa.",
    price: 24.9,
    tag: null,
    tags: "onion,rings",
  },
  {
    code: "PR-06",
    name: "Polenta Frita c/ Parmesão",
    size: "300g",
    desc: "Polenta cremosa cortada em bastões, dourada na fritura. Parmesão ralado na hora e raspas de limão.",
    price: 26.9,
    tag: "NOVO",
    tags: "polenta,fried",
  },
];

// ============================== SOBREMESAS ==============================
export const SANKA_DESSERTS = [
  {
    name: "Milkshake Ovomaltine",
    desc: "Sorvete cremoso de baunilha, leite gelado e flocos crocantes de ovomaltine batidos na hora.",
    price: 18.9,
    bg: "linear-gradient(155deg, #6a4a2a 0%, #2a1a0a 100%)",
  },
  {
    name: "Milkshake Morango",
    desc: "Morango fresco da estação, sorvete artesanal e raspas de chocolate branco por cima.",
    price: 18.9,
    bg: "linear-gradient(155deg, #c94a6a 0%, #2a0a14 100%)",
  },
  {
    name: "Brownie c/ Sorvete",
    desc: "Brownie de chocolate 70% morno, bola de sorvete de creme e calda quente de doce de leite.",
    price: 22.9,
    bg: "linear-gradient(155deg, #4a2a1a 0%, #1a0a05 100%)",
  },
];

